
<!--form action="/application/index/test" method="post">
	<fieldset>
	<legend>Inventory List :</legend>
	<label>category :</label>
	<input type="text" name="category"/><br/><br/>
	<label>sub category :</label>
	<input type="text" name="sub_category"/><br/><br/>
	
	<label>Item ID :</label>
	<input type="text" name="item_id"><br/><br/>
	<input type="submit" value="Submit"/><br/>
	</fieldset>
	
</form-->
<form action="/application/index/test" method="post">
	<fieldset>
		<legend> Category</legend>
			<select name="category">
				<option value="Bedroom">BEDROOM</option>
				<option value="Kids Room">Kids Room</option>
				<option value="Nursery">Nursery</option>
				<option value="Dining Room">Dining Room</option>
				<option value="Kitchen">Kitchen</option>
				<option value="Living Room">Living Room</option>
				<option value="Office">Office</option>
				<option value="Garage">Garage</option>
				<option value="Outdoor">Outdoor</option>
				<option value="Other">Other</option>
			</select>
			<input type="submit" value="Submit"/><br/>
	</fieldset>
</form>

