<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Got Movers Local Move Email</title>
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
<link href="https://fonts.googleapis.com/css?family=Lato:400,700&subset=latin-ext" rel="stylesheet">
<style type="text/css">
*{box-sizing:border-box;}
body {margin:0; padding:0;}
td {text-align:left; vertical-align:middle;}
@media only screen and (max-width: 600px) {
  *[class="gmail-fix"] {
    display: none !important;
  }
}
</style>
</head>
<body>
<?php $siteurl = 'http://gotmovers.eqm.bz'; ?>    
<table width="100%" border="0" cellspacing="0" cellpadding="0">
	
	<tr>
		<td>
			<table width="600" cellspacing="0" cellpadding="0" align="center" style="max-width:600px; background:#f6f6f6; padding:0; margin:0px auto; -webkit-font-smoothing:antialiased;">
				<tr>
					<td>
						<table cellspacing="0" cellpadding="0" align="center" style="width:600px; margin:0;">

							
							<tr>
								<td colspan="2" style="text-align:left; background:#fff; padding:0px 25px 0; color:#2F2F2F; font-size:16px; font-family: 'Lato', sans-serif; font-weight:400; line-height:125%;">
									Hi <?php echo $this->name;?>,<br/><br/>
									Thanks for submitting your information with GotMovers. Please see the attachment below for a copy of your inventory.
									<br/><br/>
									<br/>
									The GotMovers Team
									
								</td>
							</tr>
							<tr>
								<td colspan="2" style="text-align:left; background:#fff; padding:5px 25px 0; color:#2F2F2F; font-size:19px; font-family: 'Lato', sans-serif; font-weight:400; line-height:125%;">
								<img src="<?php echo $siteurl?>/images/inventory-logo.png"/>
								</td></tr>
								
						</table>

					</td>
				</tr>
			</table>			
		</td>
	</tr>
	
</table>
</body>
</html>
